#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HackAtHomeClient.Resource", IsApplication=true)]

namespace HackAtHomeClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HackAtHome.CustomAdapters.Resource.Animation.slide_in_right = global::HackAtHomeClient.Resource.Animation.slide_in_right;
			global::HackAtHome.CustomAdapters.Resource.Animation.slide_out_left = global::HackAtHomeClient.Resource.Animation.slide_out_left;
			global::HackAtHome.CustomAdapters.Resource.Drawable.ic_arrow_back = global::HackAtHomeClient.Resource.Drawable.ic_arrow_back;
			global::HackAtHome.CustomAdapters.Resource.Id.webview = global::HackAtHomeClient.Resource.Id.webview;
			global::HackAtHome.CustomAdapters.Resource.Layout.activity_webview = global::HackAtHomeClient.Resource.Layout.activity_webview;
			global::HackAtHome.CustomAdapters.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.CustomAdapters.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.CustomAdapters.Resource.String.title_activity_webview = global::HackAtHomeClient.Resource.String.title_activity_webview;
			global::HackAtHome.Entities.Resource.Animation.slide_in_right = global::HackAtHomeClient.Resource.Animation.slide_in_right;
			global::HackAtHome.Entities.Resource.Animation.slide_out_left = global::HackAtHomeClient.Resource.Animation.slide_out_left;
			global::HackAtHome.Entities.Resource.Drawable.ic_arrow_back = global::HackAtHomeClient.Resource.Drawable.ic_arrow_back;
			global::HackAtHome.Entities.Resource.Id.webview = global::HackAtHomeClient.Resource.Id.webview;
			global::HackAtHome.Entities.Resource.Layout.activity_webview = global::HackAtHomeClient.Resource.Layout.activity_webview;
			global::HackAtHome.Entities.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.Entities.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.Entities.Resource.String.title_activity_webview = global::HackAtHomeClient.Resource.String.title_activity_webview;
			global::HackAtHome.SAL.Resource.Animation.slide_in_right = global::HackAtHomeClient.Resource.Animation.slide_in_right;
			global::HackAtHome.SAL.Resource.Animation.slide_out_left = global::HackAtHomeClient.Resource.Animation.slide_out_left;
			global::HackAtHome.SAL.Resource.Drawable.ic_arrow_back = global::HackAtHomeClient.Resource.Drawable.ic_arrow_back;
			global::HackAtHome.SAL.Resource.Id.webview = global::HackAtHomeClient.Resource.Id.webview;
			global::HackAtHome.SAL.Resource.Layout.activity_webview = global::HackAtHomeClient.Resource.Layout.activity_webview;
			global::HackAtHome.SAL.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::HackAtHome.SAL.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::HackAtHome.SAL.Resource.String.title_activity_webview = global::HackAtHomeClient.Resource.String.title_activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::HackAtHomeClient.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::HackAtHomeClient.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::HackAtHomeClient.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::HackAtHomeClient.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::HackAtHomeClient.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::HackAtHomeClient.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::HackAtHomeClient.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::HackAtHomeClient.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060013
			public const int btnValidar = 2131099667;
			
			// aapt resource value: 0x7f060010
			public const int etEmail = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int etPassword = 2131099666;
			
			// aapt resource value: 0x7f060006
			public const int ivEvidencia = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int lvEvidences = 2131099657;
			
			// aapt resource value: 0x7f06000f
			public const int textView1 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int textView2 = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int textView4 = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int tvEvidenceName = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int tvEvidenceNameLand = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int tvEvidenceNamePort = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int tvEvidenceStatus = 2131099651;
			
			// aapt resource value: 0x7f06000c
			public const int tvEvidenceStatusLand = 2131099660;
			
			// aapt resource value: 0x7f06000e
			public const int tvEvidenceStatusPort = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int tvName = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int tvNameDetail = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int tvTitle = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int webview = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int wvDescription = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityEvidenceDetail = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActivityEvidences = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int lvTemplateLand = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int lvTemplatePort = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int Email = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int Error0 = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int EvidenceDescription = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int EvidencesTitle = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int ResultDialogTitle = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int Validate = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
